version: "3"
services:
  web:
    build: .
    container_name: envapp
    # command: gunicorn seso.wsgi:application --bind 0.0.0.0:8000
    command: python3 manage.py runserver 0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - networks
  db:
    platform: linux/x86_64
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "33403:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - volume:/var/lib/mysql
      - settings:/etc/mysql
    networks:
      - networks

networks:
  networks:

volumes:
  volume:
  settings: